### ISSUE TITLE
[1.2.0] Freezing except jog dial while editing pattern.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#294]
I tried several times, such as restarting, removing the SD card, starting it, and then returning, but if it didn't change.
So I loaded SD card into the MAC and then put it back in the tracker and it recovered.
 It's now resolved, but I'm about to lose important data, so I'll report it.
Please check the video linked.

[https://drive.google.com/file/d/15hnoLxHMi2_4AB-mYsK--i8jwjUdEXTF/view?usp=drivesdk](https://drive.google.com/file/d/15hnoLxHMi2_4AB-mYsK--i8jwjUdEXTF/view?usp=drivesdk)

**Comment by Jacknametrouble** [comment]
When trouble hits and issues persist, just remove the USB cable from its port and plug it back in. We'll investigate the issue. We may need a project where this has happened.

**Comment by modmodmodmod** [comment]
Thank you.  It is possible to send a project immediately after freezing.  However, the problem was solved by reading SDcard into the Mac, so I was able to back up the data immediately after the solution.

**Comment by takistap** [comment]
I experienced the same issue. Removing USB cable and SDcard didn't solve my issue. I had to flash the firmware and power on and off a couple of times.

**Comment by piotr3500** [comment]
fixed in 1.3
